### ISSUE TITLE
启动时中途会报NoSuchMethodError

### ISSUE THREAD

**Issue by zsdwhr** [simple-robot/simbot-mirai-spring-boot-demo#2]
部分控制台日志如下：
2021-06-13 16:36:55.343  INFO 4740 --- [           main] l.f.s.component.mirai.net.3164577443     : Successfully loaded friend list: 3 in total
2021-06-13 16:36:55.440  INFO 4740 --- [           main] l.f.s.component.mirai.net.3164577443     : Start loading group list...
2021-06-13 16:36:55.504  INFO 4740 --- [           main] l.f.s.component.mirai.net.3164577443     : Successfully loaded stranger list: 0 in total
2021-06-13 16:36:56.073  INFO 4740 --- [           main] l.f.s.component.mirai.net.3164577443     : Successfully loaded group list: 3 in total.
2021-06-13 16:36:56.076  INFO 4740 --- [           main] l.f.s.component.mirai.bot.3164577443     : Login successful
2021-06-13 16:36:56.079 ERROR 4740 --- [atcher-worker-1] l.f.s.component.mirai.net.3164577443     : Exception in NetworkHandler

java.lang.NoSuchMethodError: kotlin.time.DurationKt.getSeconds(J)D
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:218) ~[mirai-core-jvm-2.6.4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]

2021-06-13 16:36:56.079 ERROR 4740 --- [atcher-worker-2] l.f.s.component.mirai.net.3164577443     : Exception in NetworkHandler

java.lang.NoSuchMethodError: kotlin.time.DurationKt.getSeconds(J)D
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:233) ~[mirai-core-jvm-2.6.4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]

接下来是正常的登录流程，能够登录，也能发送信息
昨天晚上IDEA已经更新成2021.1.2

**Comment by ForteScarlet** [comment]
这是kotlin版本冲突导致的错误，目前来看不会过于影响程序运行，可以无视并等下个版本发布。
如果实在看着难受，可以使用高于 `v2.0.8` 的测试版本，版本号可以去 [simbot-releases](https://github.com/ForteScarlet/simpler-robot/releases) 选一个喜欢的，比如 `v2.1.0-DEV.3.2` 


以及，反馈问题我更建议去 https://github.com/ForteScarlet/simpler-robot 反馈，毕竟这里只是个demo仓库。。
